### PR TITLE
was using zeros based indexing..

### PR DESCRIPTION
**Pull request by PaulBellette**
... we should probably be using 1 based indexing.

### CODE REVIEW

**Review by andyferris — APPROVED** [review]
Seems consistent

**Comment by OmriTreidel** [comment]
Did you write a test for it?

**Comment by PaulBellette** [comment]
I did write some tests, but on seconds thoughts (i.e. talking to @c42f ) this is not the problem that I thought it was. It is sort of irrelevant how we encode the key to the dict, we should have a function that returns a key for a given point and this should be exposed so if we want to find the points that are in a given pixel we ask that function for the key, then use the key to get the nearby points.

**Comment by JoshChristie** [comment]
For reference some of this functionality exists for 3D voxels, see `sparse_voxels.jl`. A lot of it could be reworked to apply for 2D but it might be better to rewrite it.

`make_voxel_id(point, voxel_size)` is a function which returns a 3D key/id for a given point.
`SparseVoxelGrid` returns a `Voxel` which is an iterator that returns point indices.

```julia
julia> grid = SparseVoxelGrid(points, 10.0)

julia> grid[(0,1,0)]
SpatialGrids.Voxel (0,1,0) with 12437 points

julia> collect(grid[(0,1,0)])
12437-element Array{Int64,1}:
 99999
 99975
 99946
...
etc
```

**Pull request closed without merging**
