### PR TITLE
Upgrade to 1 0 jessie

### PR DESCRIPTION
**Pull request by JessieMcVicar**
Updated julia version.

### CODE REVIEW

**Comment by JoshChristie** [comment]
Nice, looks good. Have you tested whether there were improvements in speed the interators, particularly `in_cuboid`?

**Comment by JoshChristie** [comment]
Update travis and appveyor files to build 1.0

**Review by PrabodhaSrimal — APPROVED** [review]

**Comment by msbahal** [comment]
> Nice, looks good. Have you tested whether there were improvements in speed the interators, particularly `in_cuboid`?

I ran a quick test of the in_cuboid function and was actually surprised by the performace of the SparseVoxelGrid function.

I ran the following with rand to use the same seed value:
```
points3d = rand(rng, Float64, 3, 10000000) .* 10000.0

@time grid = SparseVoxelGrid(points3d, 2.0)

voxel_list = [ (100,100,100)]

@time length(collect(in_cuboid(grid, voxel_list[1], 2)))
```

The second line took 41.29 secs for the v1.0 package whereas it took 92.13 secs for the older package. 

The fourth line took 0.00014 secs in v1.0 whereas it took 0.000056 secs for v0.6. This was on the second and subsequent function call. First query always took way longer.

I think the gain from second line definitely outweights the loss in the fourth line. What say?

Also could I get an approve if you're happy with the results and code @JoshChristie @prabodha007

**Comment by msbahal** [comment]
> Update travis and appveyor files to build 1.0

Travis and Appveyor tests pass now!

**Comment by JoshChristie** [comment]
Looks like a nice gain.

**Review by JoshChristie — APPROVED** [review]

**Review by msbahal — APPROVED** [review]

**Pull request merged**
